### ISSUE TITLE
Theme Conflict

### ISSUE THREAD

**Issue by stsjon** [clakeb/custom-business-locations#1]
Hello,

Love the plugin, it's truely amazing. My only problem is that I cannot change my theme readily. I have tried 5 different themes and none of them work. When I go to that page, nothing shows, its completely blank. When I use the default Twenty Twelve theme, however, it works fine. 

I've seen other plugins describe similar errors related to jQuery is that helps.

**Comment by tatemz** [comment]
Hi,  

Thanks for the report. I received a similar bug report on Monday.  I am actually working on a more complete version at this very moment.  Please note that I simply published that plugin as an after thought after building it for a customer.  Of course, it worked on that customer's site, but I can see that it breaks on other themes (primarily due to some jQuery overriding).  You should see an update soon!  

## 

A. Tate Barber
