### ISSUE TITLE
No Maps

### ISSUE THREAD

**Issue by stsjon** [clakeb/custom-business-locations#3]
After updating to newest version, no maps will show, for any locations. 

Link: http://goo.gl/P44FS

**Comment by stsjon** [comment]
Additionally: I cannot select locations, nor do phone numbers show.

**Comment by tatemz** [comment]
Everything working on my install... including displaying phone numbers.  Have you tried deactivating all other plugins?  Sometimes other plugins make the same mistake I did in the previous version by overriding jQuery.  Deactivating other plugins one by one should narrow it down. The latest update to my plugin includes no jQuery overrides, no extra javascript other than simple jQuery and WordPress ajax calls. You may have lost some data during the upgrade process ( I tried preserving everything that I could ) due to the fact that I opted to do all configurations and location creating from within the plugin settings rather than with custom post types. Just re-create the locations from within the new interface and all should be well. Also your link shows a database error.

Can you pull up any javascript consoles that might be showing javascript errors either on the admin page or the frontend?

**Comment by stsjon** [comment]
Everything worked great after I completed deleted and reinstalled my site. Must have been a database issue; now that I have it opened:

I love the new settings page, much easier, the only thing I might suggest is adding a line for a secondary number or a fax number. 

I can't wait to get a business client that needs this, as soon as I do your getting a donation.

**Comment by tatemz** [comment]
Thanks.

I'll see what I can do about a secondary number.
